#include "assert.h"

#include "FileAccess.h"
#include "Constants.h"

Element::Element(const tinyxml2::XMLElement *pElement)
	: m_pElement(pElement)
{
}

bool Element::isValid() const
{
	return m_pElement != NULL;
}

const char* Element::name() const
{
	assert(isValid());
	return m_pElement->Name();
}

int Element::numChildren() const
{
	assert(isValid());

	int count = 0;
	for (const tinyxml2::XMLElement* element = m_pElement->FirstChildElement(); element != NULL; element = element->NextSiblingElement())
	{
		++count;
	}

	return count;
}

bool Element::hasMultipleChildren() const
{
	const tinyxml2::XMLElement* element = m_pElement->FirstChildElement();
	if (element == NULL)
	{
		return false;
	}
	return element->NextSiblingElement() != NULL;
}

Element Element::FirstChild(const char* name)
{
	assert(isValid());
	return Element(m_pElement->FirstChildElement(name));
}

const Element Element::FirstChild(const char* name) const
{
	assert(isValid());
	return Element(m_pElement->FirstChildElement(name));
}

Element Element::NextSibling(const char* name)
{
	assert(isValid());
	return Element(m_pElement->NextSiblingElement(name));
}

const Element Element::NextSibling(const char* name) const
{
	assert(isValid());
	return Element(m_pElement->NextSiblingElement(name));
}

bool Element::getBool() const
{
	assert(isValid());
	return m_pElement->BoolText();
}

int Element::getInt() const
{
	assert(isValid());
	return m_pElement->IntText();
}

const char* Element::getText() const
{
	assert(isValid());
	return m_pElement->GetText();
}

const char* Element::Attribute(const char* name)
{
	return m_pElement->Attribute(name);
}

LineString sourcePath;


void TextFile::setup()
{
	assert(sourcePath.size() == 0);
	TextFile file("Makefile.project", FileLocation::FILE_LOCATION_ROOT);

	while (file.hasLinesLeft())
	{
		sourcePath = file.readLine();

		if (sourcePath.compare(0, 11, "SOURCE_DIR"))
		{
			sourcePath.erase(0, 10);
			sourcePath.killLeadingWhitespace();
			sourcePath.killFirstChar('=');
			sourcePath.killLeadingWhitespace();
			sourcePath.append("/");
			break;
		}
	}
}


static std::string getDir(FileLocation::locations location)
{
	switch (location)
	{
	case FileLocation::FILE_LOCATION_ROOT:
		return "";
	case FileLocation::FILE_LOCATION_SOURCE:
		return sourcePath + "/";
	case FileLocation::FILE_LOCATION_AUTO:
		return sourcePath + "/autogenerated/";
	case FileLocation::FILE_LOCATION_XML:
		return XML_DIR;
	}
	assert(false);
	return "";
}

static std::string createPath(const char* file, FileLocation::locations location)
{
	std::string path(getDir(location));
	path.append(file);
	return path;
}

FileAccessXML::FileAccessXML(const char* FileName)
	: m_Filename(FileName)
	, m_pElement(NULL)
{
	std::string file = XML_DIR;
	file.append(m_Filename);

	m_Doc.LoadFile(file.c_str());
	if (m_Doc.Error())
	{
		// try opening vanilla instead
		file = getDir(FileLocation::FILE_LOCATION_ROOT);
		file.append("../../");
		file.append(XML_DIR);
		file.append(m_Filename);
		m_Doc.LoadFile(file.c_str());
	}
}

Element FileAccessXML::getRoot() const
{
	const tinyxml2::XMLElement* element = m_Doc.FirstChildElement();
	return Element(element);
}


TextFile::TextFile(const char* filename, FileLocation::locations location)
	: file(createPath(filename, location).c_str())
	, line_number(0)
{
	assert(file.is_open());
}

TextFile::~TextFile()
{
	file.close();
}

LineString TextFile::readLine()
{
	++line_number;

	std::string buffer;
	std::getline(file, buffer);
	return buffer;
}

unsigned int TextFile::getLineNumber() const
{
	return line_number;
}

bool TextFile::hasLinesLeft() const
{
	return !file.eof();
}
