#include <fstream>
#include <string>
#include <iostream>
#include <streambuf>

#include "OutputHandler.h"

OutputHandler::OutputHandler()
	: m_indent(0)
{
}

void OutputHandler::addStartBracket()
{
	printLine("{");
	changeIndent(1);
}

void OutputHandler::addEndBracket(bool bAddSemicolon)
{
	changeIndent(-1);
	if (bAddSemicolon)
	{
		printLine("};");
	}
	else
	{
		printLine("}");
	}
}

void OutputHandler::printLine()
{
	m_text.append("\n");
}

void OutputHandler::printLine(const char* A)
{
	addIndent();
	m_text.append(A);
	m_text.append("\n");
}

void OutputHandler::printLine(const char* A, const char* B)
{
	addIndent();
	m_text.append(A);
	m_text.append(B);
	m_text.append("\n");
}

void OutputHandler::printLine(const char* A, const char* B, const char* C)
{
	addIndent();
	m_text.append(A);
	m_text.append(B);
	m_text.append(C);
	m_text.append("\n");
}

void OutputHandler::printLine(const char* A, const char* B, const char* C, const char* D)
{
	addIndent();
	m_text.append(A);
	m_text.append(B);
	m_text.append(C);
	m_text.append(D);
	m_text.append("\n");
}

void OutputHandler::printLine(const char* A, const char* B, const char* C, const char* D, const char* E)
{
	addIndent();
	m_text.append(A);
	m_text.append(B);
	m_text.append(C);
	m_text.append(D);
	m_text.append(E);
	m_text.append("\n");
}

void OutputHandler::printLine(const char* A, const char* B, const char* C, const char* D, const char* E, const char* F)
{
	addIndent();
	m_text.append(A);
	m_text.append(B);
	m_text.append(C);
	m_text.append(D);
	m_text.append(E);
	m_text.append(F);
	m_text.append("\n");
}

void OutputHandler::printLine(const char* A, const char* B, const char* C, const char* D, const char* E, const char* F, const char* G)
{
	addIndent();
	m_text.append(A);
	m_text.append(B);
	m_text.append(C);
	m_text.append(D);
	m_text.append(E);
	m_text.append(F);
	m_text.append(G);
	m_text.append("\n");
}

void OutputHandler::printLine(const char* A, const char* B, const char* C, const char* D, const char* E, const char* F, const char* G, const char* H)
{
	addIndent();
	m_text.append(A);
	m_text.append(B);
	m_text.append(C);
	m_text.append(D);
	m_text.append(E);
	m_text.append(F);
	m_text.append(G);
	m_text.append(H);
	m_text.append("\n");
}
void OutputHandler::printLine(const char* A, const char* B, const char* C, const char* D, const char* E, const char* F, const char* G, const char* H, const char* I)
{
	addIndent();
	m_text.append(A);
	m_text.append(B);
	m_text.append(C);
	m_text.append(D);
	m_text.append(E);
	m_text.append(F);
	m_text.append(G);
	m_text.append(H);
	m_text.append(I);
	m_text.append("\n");
}

void OutputHandler::printLineNoIndent(const char* A)
{
	m_text.append(A);
	m_text.append("\n");
}

void OutputHandler::printLineRemoveLastChar(const char* A, const char* B)
{
	addIndent();
	m_text.append(A);
	std::string temp = B;
	temp.resize(temp.size() - 1);
	m_text.append(temp);
	m_text.append("\n");
}

void OutputHandler::changeIndent(int iChange)
{
	m_indent += iChange;
}

void OutputHandler::addIndent()
{
	switch (m_indent)
	{
		// switch case as it executes faster than a loop. 
	case 0: return;
	case 1: m_text.append("\t"); return;
	case 2: m_text.append("\t\t"); return;
	case 3: m_text.append("\t\t\t"); return;
	case 4: m_text.append("\t\t\t\t"); return;
	case 5: m_text.append("\t\t\t\t\t"); return;
	case 6: m_text.append("\t\t\t\t\t\t"); return;

	}
}

void OutputHandler::saveFile(const char* filenameA, const char* filenameB, const char* filenameC)
{
	std::string name = "DLLSources/autogenerated/AUTO_";
	name.append(filenameA);
	name.append(filenameB);
	name.append(filenameC);

	std::ifstream t(name.c_str());

	if (t.is_open())
	{
		// compare with existing file
		std::string str;
		t.seekg(0, std::ios::end);
		str.reserve(t.tellg());
		t.seekg(0, std::ios::beg);

		str.assign((std::istreambuf_iterator<char>(t)),
			std::istreambuf_iterator<char>());

		if (m_text == str)
		{
			// the file is already up to date. Bail out before touching the modification date
			return;
		}
	}

	std::ofstream out(name.c_str());
	out << m_text;
	out.close();
}
