#include <fstream>
#include <string>
#include <iostream>
#include <streambuf>

#include "OutputHandler.h"

OutputHandler::OutputHandler()
	: m_indent(0)
{
}

void OutputHandler::addStartBracket()
{
	printLine("{");
	changeIndent(1);
}

void OutputHandler::addEndBracket()
{
	changeIndent(-1);
	printLine("}");
}

void OutputHandler::printLine(const char* A)
{
	addIndent();
	m_text.append(A);
	m_text.append("\n");
}

void OutputHandler::printLine(const char* A, const char* B)
{
	addIndent();
	m_text.append(A);
	m_text.append(B);
	m_text.append("\n");
}

void OutputHandler::printLine(const char* A, const char* B, const char* C)
{
	addIndent();
	m_text.append(A);
	m_text.append(B);
	m_text.append(C);
	m_text.append("\n");
}

void OutputHandler::printLineNoIndent(const char* A)
{
	m_text.append(A);
	m_text.append("\n");
}

void OutputHandler::printLineRemoveLastChar(const char* A, const char* B)
{
	addIndent();
	m_text.append(A);
	std::string temp = B;
	temp.resize(temp.size() - 1);
	m_text.append(temp);
	m_text.append("\n");
}

void OutputHandler::changeIndent(int iChange)
{
	m_indent += iChange;
}

void OutputHandler::addIndent()
{
	switch (m_indent)
	{
		// no breaks. Fall through as this way it will add one for each number
		// this causes less overhead than a loop
	case 0: return;
	case 1: m_text.append("\t"); return;
	case 2: m_text.append("\t\t"); return;
	case 3: m_text.append("\t\t\t"); return;
	case 4: m_text.append("\t\t\t\t"); return;
	case 5: m_text.append("\t\t\t\t\t"); return;
	case 6: m_text.append("\t\t\t\t\t\t"); return;

	}
}

void OutputHandler::saveFile(const char* filenameA, const char* filenameB, const char* filenameC)
{
	std::string name = "DLLSources/autogenerated/AUTO_";
	name.append(filenameA);
	name.append(filenameB);
	name.append(filenameC);

	std::ifstream t(name.c_str());

	if (t.is_open())
	{
		// compare with existing file
		std::string str;
		t.seekg(0, std::ios::end);
		str.reserve(t.tellg());
		t.seekg(0, std::ios::beg);

		str.assign((std::istreambuf_iterator<char>(t)),
			std::istreambuf_iterator<char>());

		if (m_text == str)
		{
			// the file is already up to date. Bail out before touching the modification date
			return;
		}
	}

	std::ofstream out(name.c_str());
	out << m_text;
	out.close();
}
