#include <Windows.h>
#include <fstream>
#include <iostream>
#include <sstream> //std::stringstream

#include "SourceReader.h"
#include "Constants.h"


SourceFileContainer::SourceFileContainer(std::string fileWName)
	: m_filename(fileWName)
{
}

const std::string& SourceFileContainer::getText() const
{
	return m_fileAsString;
}

void SourceFileContainer::setup()
{
	std::ifstream inFile;
	inFile.open(m_filename.c_str()); //open the input file

	std::stringstream strStream;
	strStream << inFile.rdbuf(); //read the file
	m_fileAsString = strStream.str(); //copy the file content into the string
}


//
//
//      SourceFileList
//
//

SourceFileList instance;

SourceFileList::SourceFileList()
{
	readDir(SOURCE_DIR);

	for (std::vector<SourceFileContainer>::iterator it = m_files.begin(); it != m_files.end(); it++)
	{
		it->setup();
	}
}

const SourceFileList& SourceFileList::getInstance()
{
	return instance;
}

const std::vector<SourceFileContainer>& SourceFileList::getFiles() const
{
	return m_files;
}

void SourceFileList::readDir(std::string path)
{
	std::string search_path = path +"*";
	WIN32_FIND_DATA fd;
	HANDLE hFind = ::FindFirstFile(search_path.c_str(), &fd);
	if (hFind != INVALID_HANDLE_VALUE) {
		do {
			const char* name = fd.cFileName;
			if (name[0] == '.')
			{
				// skip hidden files and folders
				continue;
			}

			std::string fullPath = path + name;


			if (fd.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY)
			{
				if (strcmp(name, "autogenerated") == 0 || strcmp(name, "lib") == 0)
				{
					// don't enter the autogenerated dir
					continue;
				}

				fullPath.append("/");
				readDir(fullPath);
			}
			else
			{
				m_files.push_back(SourceFileContainer(fullPath));
			}
		} while (::FindNextFile(hFind, &fd));
		::FindClose(hFind);
	}
}
