#pragma once

#include "../autogenerated/AutoXmlEnum.h"

class CvBuildInfo;

class LoopBuildTypes
{
public:
	LoopBuildTypes();
	LoopBuildTypes(BuildTypes type);
	BuildTypes value() const;

	bool isValid() const;
	bool next();

	const CvBuildInfo& info() const;
	operator BuildTypes() const;

	static LoopBuildTypes createFromInt(int iIndex);

	static const CvBuildInfo& info(BuildTypes eBuild);
protected:
	BuildTypes data;
};

class RouteBuildTypes : public LoopBuildTypes
{
public:
	RouteBuildTypes();
	RouteBuildTypes(BuildTypes type);

	bool isValid() const;
	bool next();

	static LoopBuildTypes createFromInt(int iIndex);
};
