// File for overriding function implementations for the autogenerated type classes, such as Yieldtype.
// Writing a function in this file will make Autogenerate.exe skip generating said function.
// In other words it's possible to generate custom functions as needed without changing Autogenerate.exe
// Note that setupCustom is added for this specific purpose and is always empty in autogenerated files.
