#include "CvGameCoreDLL.h"

//
// File responsbile for building project PCH
//

//
// Test that enum values hardcoded in the exe stays at what the exe expects.
// While we do not know precisely which values are hardcoded we do know that some are.
// If a value is hardcoded, add the entire enum here just to be safe.
//    Nightinggale
//

BOOST_STATIC_ASSERT(WIDGET_PLOT_LIST == WidgetTypes(0));
BOOST_STATIC_ASSERT(WIDGET_PLOT_LIST_SHIFT == WidgetTypes(1));
BOOST_STATIC_ASSERT(WIDGET_CITY_SCROLL == WidgetTypes(2));
BOOST_STATIC_ASSERT(WIDGET_LIBERATE_CITY == WidgetTypes(3));
BOOST_STATIC_ASSERT(WIDGET_CITY_NAME == WidgetTypes(4));
BOOST_STATIC_ASSERT(WIDGET_UNIT_NAME == WidgetTypes(5));
BOOST_STATIC_ASSERT(WIDGET_CREATE_GROUP == WidgetTypes(6));
BOOST_STATIC_ASSERT(WIDGET_DELETE_GROUP == WidgetTypes(7));
BOOST_STATIC_ASSERT(WIDGET_TRAIN == WidgetTypes(8));
BOOST_STATIC_ASSERT(WIDGET_CONSTRUCT == WidgetTypes(9));
BOOST_STATIC_ASSERT(WIDGET_CONVINCE == WidgetTypes(10));
BOOST_STATIC_ASSERT(WIDGET_HURRY == WidgetTypes(11));
BOOST_STATIC_ASSERT(WIDGET_PLAYER_HURRY == WidgetTypes(12));
BOOST_STATIC_ASSERT(WIDGET_MENU_ICON == WidgetTypes(13));
BOOST_STATIC_ASSERT(WIDGET_ACTION == WidgetTypes(14));
BOOST_STATIC_ASSERT(WIDGET_CITIZEN == WidgetTypes(15));
BOOST_STATIC_ASSERT(WIDGET_CONTACT_CIV == WidgetTypes(16));
BOOST_STATIC_ASSERT(WIDGET_SCORE_BREAKDOWN == WidgetTypes(17));
BOOST_STATIC_ASSERT(WIDGET_ZOOM_CITY == WidgetTypes(18));
BOOST_STATIC_ASSERT(WIDGET_END_TURN == WidgetTypes(19));
BOOST_STATIC_ASSERT(WIDGET_AUTOMATE_CITIZENS == WidgetTypes(20));
BOOST_STATIC_ASSERT(WIDGET_AUTOMATE_PRODUCTION == WidgetTypes(21));
BOOST_STATIC_ASSERT(WIDGET_EMPHASIZE == WidgetTypes(22));
BOOST_STATIC_ASSERT(WIDGET_DIPLOMACY_RESPONSE == WidgetTypes(23));
BOOST_STATIC_ASSERT(WIDGET_GENERAL == WidgetTypes(24));
BOOST_STATIC_ASSERT(WIDGET_FILE_LISTBOX == WidgetTypes(25));
BOOST_STATIC_ASSERT(WIDGET_FILE_EDITBOX == WidgetTypes(26));
BOOST_STATIC_ASSERT(WIDGET_WB_UNITNAME_EDITBOX == WidgetTypes(27));
BOOST_STATIC_ASSERT(WIDGET_WB_CITYNAME_EDITBOX == WidgetTypes(28));
BOOST_STATIC_ASSERT(WIDGET_WB_SAVE_BUTTON == WidgetTypes(29));
BOOST_STATIC_ASSERT(WIDGET_WB_LOAD_BUTTON == WidgetTypes(30));
BOOST_STATIC_ASSERT(WIDGET_WB_ALL_PLOTS_BUTTON == WidgetTypes(31));
BOOST_STATIC_ASSERT(WIDGET_WB_LANDMARK_BUTTON == WidgetTypes(32));
BOOST_STATIC_ASSERT(WIDGET_WB_ERASE_BUTTON == WidgetTypes(33));
BOOST_STATIC_ASSERT(WIDGET_WB_EXIT_BUTTON == WidgetTypes(34));
BOOST_STATIC_ASSERT(WIDGET_WB_UNIT_EDIT_BUTTON == WidgetTypes(35));
BOOST_STATIC_ASSERT(WIDGET_WB_CITY_EDIT_BUTTON == WidgetTypes(36));
BOOST_STATIC_ASSERT(WIDGET_WB_NORMAL_PLAYER_TAB_MODE_BUTTON == WidgetTypes(37));
BOOST_STATIC_ASSERT(WIDGET_WB_NORMAL_MAP_TAB_MODE_BUTTON == WidgetTypes(38));
BOOST_STATIC_ASSERT(WIDGET_WB_REVEAL_TAB_MODE_BUTTON == WidgetTypes(39));
BOOST_STATIC_ASSERT(WIDGET_WB_DIPLOMACY_MODE_BUTTON == WidgetTypes(40));
BOOST_STATIC_ASSERT(WIDGET_WB_REVEAL_ALL_BUTTON == WidgetTypes(41));
BOOST_STATIC_ASSERT(WIDGET_WB_UNREVEAL_ALL_BUTTON == WidgetTypes(42));
BOOST_STATIC_ASSERT(WIDGET_WB_REGENERATE_MAP == WidgetTypes(43));
BOOST_STATIC_ASSERT(WIDGET_TRADE_ITEM == WidgetTypes(44));
BOOST_STATIC_ASSERT(WIDGET_UNIT_MODEL == WidgetTypes(45));
BOOST_STATIC_ASSERT(WIDGET_POPUP_QUEUE == WidgetTypes(46));
BOOST_STATIC_ASSERT(WIDGET_PYTHON == WidgetTypes(47));
BOOST_STATIC_ASSERT(WIDGET_HELP_DEFENSE == WidgetTypes(48));
BOOST_STATIC_ASSERT(WIDGET_HELP_POPULATION == WidgetTypes(49));
BOOST_STATIC_ASSERT(WIDGET_HELP_REBEL == WidgetTypes(50));
BOOST_STATIC_ASSERT(WIDGET_HELP_GREAT_GENERAL == WidgetTypes(51));
BOOST_STATIC_ASSERT(WIDGET_HELP_SELECTED == WidgetTypes(52));
BOOST_STATIC_ASSERT(WIDGET_HELP_YIELD == WidgetTypes(53));
BOOST_STATIC_ASSERT(WIDGET_HELP_PROMOTION == WidgetTypes(54));
BOOST_STATIC_ASSERT(WIDGET_HELP_UNIT_PROMOTION == WidgetTypes(55));
BOOST_STATIC_ASSERT(WIDGET_CHOOSE_EVENT == WidgetTypes(56));
BOOST_STATIC_ASSERT(WIDGET_PEDIA_JUMP_TO_UNIT == WidgetTypes(57));
BOOST_STATIC_ASSERT(WIDGET_PEDIA_JUMP_TO_PROFESSION == WidgetTypes(58));
BOOST_STATIC_ASSERT(WIDGET_PEDIA_JUMP_TO_BUILDING == WidgetTypes(59));
BOOST_STATIC_ASSERT(WIDGET_PEDIA_BACK == WidgetTypes(60));
BOOST_STATIC_ASSERT(WIDGET_PEDIA_FORWARD == WidgetTypes(61));
BOOST_STATIC_ASSERT(WIDGET_PEDIA_JUMP_TO_BONUS == WidgetTypes(62));
BOOST_STATIC_ASSERT(WIDGET_PEDIA_MAIN == WidgetTypes(63));
BOOST_STATIC_ASSERT(WIDGET_PEDIA_JUMP_TO_PROMOTION == WidgetTypes(64));
BOOST_STATIC_ASSERT(WIDGET_PEDIA_JUMP_TO_IMPROVEMENT == WidgetTypes(65));
BOOST_STATIC_ASSERT(WIDGET_PEDIA_JUMP_TO_CIVIC == WidgetTypes(66));
BOOST_STATIC_ASSERT(WIDGET_PEDIA_JUMP_TO_CIV == WidgetTypes(67));
BOOST_STATIC_ASSERT(WIDGET_PEDIA_JUMP_TO_LEADER == WidgetTypes(68));
BOOST_STATIC_ASSERT(WIDGET_PEDIA_JUMP_TO_TERRAIN == WidgetTypes(69));
BOOST_STATIC_ASSERT(WIDGET_PEDIA_JUMP_TO_YIELDS == WidgetTypes(70));
BOOST_STATIC_ASSERT(WIDGET_PEDIA_JUMP_TO_FEATURE == WidgetTypes(71));
BOOST_STATIC_ASSERT(WIDGET_PEDIA_JUMP_TO_FATHER == WidgetTypes(72));
BOOST_STATIC_ASSERT(WIDGET_TURN_EVENT == WidgetTypes(73));
BOOST_STATIC_ASSERT(WIDGET_PEDIA_DESCRIPTION == WidgetTypes(74));
BOOST_STATIC_ASSERT(WIDGET_PEDIA_DESCRIPTION_NO_HELP == WidgetTypes(75));
BOOST_STATIC_ASSERT(WIDGET_DEAL_KILL == WidgetTypes(76));
BOOST_STATIC_ASSERT(WIDGET_MINIMAP_HIGHLIGHT == WidgetTypes(77));
BOOST_STATIC_ASSERT(WIDGET_PRODUCTION_MOD_HELP == WidgetTypes(78));
BOOST_STATIC_ASSERT(WIDGET_LEADERHEAD == WidgetTypes(79));
BOOST_STATIC_ASSERT(WIDGET_LEADER_LINE == WidgetTypes(80));
BOOST_STATIC_ASSERT(WIDGET_CLOSE_SCREEN == WidgetTypes(81));
BOOST_STATIC_ASSERT(WIDGET_GLOBELAYER == WidgetTypes(82));
BOOST_STATIC_ASSERT(WIDGET_GLOBELAYER_OPTION == WidgetTypes(83));
BOOST_STATIC_ASSERT(WIDGET_GLOBELAYER_TOGGLE == WidgetTypes(84));
BOOST_STATIC_ASSERT(WIDGET_CITY_UNIT_ASSIGN_PROFESSION == WidgetTypes(85));
BOOST_STATIC_ASSERT(WIDGET_MOVE_CARGO_TO_CITY == WidgetTypes(86));
BOOST_STATIC_ASSERT(WIDGET_RECEIVE_MOVE_CARGO_TO_CITY == WidgetTypes(87));
BOOST_STATIC_ASSERT(WIDGET_MOVE_CARGO_TO_TRANSPORT == WidgetTypes(88));
BOOST_STATIC_ASSERT(WIDGET_RECEIVE_MOVE_CARGO_TO_TRANSPORT == WidgetTypes(89));
BOOST_STATIC_ASSERT(WIDGET_CREATE_TRADE_ROUTE == WidgetTypes(90));
BOOST_STATIC_ASSERT(WIDGET_EDIT_TRADE_ROUTE == WidgetTypes(91));
BOOST_STATIC_ASSERT(WIDGET_YIELD_IMPORT_EXPORT == WidgetTypes(92));
BOOST_STATIC_ASSERT(WIDGET_ASSIGN_CITIZEN_TO_PLOT == WidgetTypes(93));
BOOST_STATIC_ASSERT(WIDGET_ASSIGN_TRADE_ROUTE == WidgetTypes(94));
BOOST_STATIC_ASSERT(WIDGET_EJECT_CITIZEN == WidgetTypes(95));
BOOST_STATIC_ASSERT(WIDGET_SHIP_CARGO == WidgetTypes(96));
BOOST_STATIC_ASSERT(WIDGET_DOCK == WidgetTypes(97));
BOOST_STATIC_ASSERT(WIDGET_SAIL == WidgetTypes(98));
BOOST_STATIC_ASSERT(WIDGET_GOTO_CITY == WidgetTypes(99));

