
#include "CvGameCoreDLL.h"



#include "autogenerated\AutoVariableFunctionsCPP.h"
#include "autogenerated\AutoGlobalDefineEnumCpp.h"

int getIndexOfType(JITarrayTypes eJITtype, const char* szType)
{
	switch (eJITtype)
	{
#include "autogenerated\AutoVariableFunctionsCase.h"
#include "autogenerated\AutoGlobalDefineEnumCase.h"
	};

	FAssertMsg(false, "Unhandled case");
	return -1;
}
