#include <vector>
#include "autogenerated/AUTO_InfoArray.h"

class CvInfoArrayInit
{
public:
	CvInfoArrayInit(const std::vector<int>& vec, char(&m_Array_char)[4], unsigned char(&m_Array_uchar)[4], short(&m_Array_short)[2], char*& m_pArray_char, unsigned char*& m_pArray_uchar, short*& m_pArray_short);
	InfoArrayTypes::ArrayType getType() const;
	int getExtra() const;

private:
	const std::vector<int>& m_vec;
	InfoArrayTypes::ArrayType m_ArrayType;
	int m_iExtra;
};
